USFSOURCE :=\
UserFunctions/Alpha_3.F90\
UserFunctions/COMPUTE_SSA_NODAL_Bdrag.F90\
UserFunctions/Geometry.F90\
UserFunctions/USF_Bedrock.F90\
UserFunctions/USF_Damage.F90\
UserFunctions/USF_GroundedAreaCoeff.F90\
UserFunctions/USF_HydroTrans.F90\
UserFunctions/USF_MoulinFeed.F90\
UserFunctions/USF_ReadFileData.F90\
UserFunctions/USF_TransferCoupling.F90\
UserFunctions/USFs.F90\
UserFunctions/Adjoint_USFs_LionelTMP.F90\
UserFunctions/MinusA.F90\
UserFunctions/USF_BasalMeltPDC_ASE.F90\
UserFunctions/USF_WaterPressure.F90
